Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.69.10"

  config.vm.synced_folder "../", "/vagrant/bootstrap-php"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.provision "shell", path: "./provision.sh"

  # Config ends here #

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. 
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Enable provisioning with a shell script. Can also use other provisioners
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
